sql:
  host: localhost
  port: 3306
  database: sparky
  authentication:
    username: root
    password: 'YourShittyPassword'
sync:
  # Available types:
  # - SQL: for SQL Messaging
  # - PLUGIN: for Plugin Messaging
  type: PLUGIN
  ban-command: 'ban %player% Cheating' # For BungeeCord plugin only.
  kick-message: '&cAntiCheat removed you for cheating!' # For Spigot plugin only.